### PR TITLE
no longer needs EZ2 to be on C: drive

### PR DESCRIPTION
**Pull request by tairasoul**
scan through all drives to find steamapps, then get EZ2 and the coop mod.

my build made a .dll and i cant remove it so latest release will have to be a zipped file

### CODE REVIEW

**Comment by Myrkie** [comment]
when building make sure to build as a console app and not a class Library to get a console app build

**Comment by tairasoul** [comment]
i did, i meant it was a .exe and a .dll instead of just a single .exe, wording was a bit off.
what version of visual studio did you use (if any) to only get a .exe? can't seem to figure out how to make vs 2022 only output a .exe

**Comment by Myrkie** [comment]
I dont use VS, i use Jetbrains Rider, if its a single EXE that means its being published if you can verify your changes function then ill go ahead and push this PR

**Comment by tairasoul** [comment]
yeah, works fine. game launched properly and no errors from the console app

**Comment by Myrkie** [comment]
has been merged cheers

**Pull request merged**
